currentLang: "english"

broadcastWin: true
holographicRanking: false
lightnings: true
standingLimit: true
tpToLastLoc: false

timer:
  start: 30
  blockStanding: 7
sql:
  tableName: "spleef"
reward:
  win: -1
  loose: -1