name: Spleef
version: 2.0.20
api-version: 1.12.2
author: [Naruse, jeremaier]
main: fr.naruse.spleef.main.SpleefPlugin
softdepend: [DBAPI, Vault, HolographicDisplays]
commands:
  spleef:
    description: All commands for Spleef